---
title: "heatshock analysis"
author: "Aditi Goyal"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message=FALSE)
#knitr::opts_chunk$set(warning =FALSE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=70), tidy=TRUE)

rm(list=ls())

library(tidyverse)
library(dplyr)
library(tibble)
library(DESeq2)
library(EnhancedVolcano)
library(readxl)
library(umap)
library(pheatmap)
library(dendextend)
library(colorspace)
library(clusterProfiler)
library(ggupset)
library(enrichplot)
library(eulerr)
library(pathview)
library("gridExtra")
```

```{r}
setwd('~/Desktop/KAISHA')
```

```{r}
all=read_tsv('featurecounts_rev/rnaseq_round1/rnaseq_round1.featurecounts.gene_name_extended_annot.tsv')
all=as.data.frame(all)

#split data into a gene_metadata set and the raw counts matrix
gene_meta=all[, 1:8]
counts=all[, c(1, 9:17)]

#load sample metadata
meta=read.csv('mappings/heatshock_metadata.csv')
meta
```

# Data Preprocessing
```{r}
#remove blank genes
counts=counts %>% relocate(c('HS1', 'HS2', 'HS3'), .after=Geneid)
head(counts)
```

# Starting deseq pipeline


### step 1: creating the object
```{r}
dds=DESeqDataSetFromMatrix(countData=counts, 
                              colData=meta, 
                              design=~group, tidy = TRUE)

dds$group <- relevel(dds$group, ref = "A")
```

### step 2: filtering out low count genes
```{r}
keep <- rowSums(counts(dds)) > 0
dds <- dds[keep,]
```

```{r}
### step 3: run deseq
dds <- DESeq(dds)
res <- results(dds) #this is the same as ramesh
```

```{r}
resultsNames(dds)
```
```{r}
normalized_counts <- counts(dds, normalized=TRUE)
#write.table(normalized_counts, file="heatshock_normalized_counts.txt", sep="\t", quote=F, col.names=NA)
```

```{r}
B_A <- as.data.frame(lfcShrink(dds, coef = 2, type = 'apeglm'))
C_A <- as.data.frame(lfcShrink(dds, coef = 3, type = 'apeglm'))
H_A <- as.data.frame(lfcShrink(dds, coef = 4, type = 'apeglm'))
#write.csv(H_A, 'heatshock_deseq.csv')
```

```{r}
normalized_counts <- counts(dds, normalized=TRUE)
#write.table(normalized_counts, file="data/normalized_counts.txt", sep="\t", quote=F, col.names=NA)
```


```{r}
HA_sig=H_A%>%filter(padj<=0.05)%>%filter(abs(log2FoldChange)>=1.5)%>%arrange(desc(log2FoldChange))%>%select(log2FoldChange, padj)%>%rownames_to_column('Gene')

#write.csv(HA_sig, 'DEGs/heatshock_DEGs.csv')
```

```{r}
padj.cutoff <- 0.05
lfc.cutoff <- 1.5 #log2Fold change = 1.5
```

# Volcano Plot

```{r}
H_A=H_A %>% mutate(color=case_when(
  log2FoldChange<=-1.5 ~ 'blue',
  log2FoldChange>=1.5 ~'tomato2',
  .default = 'grey'))

colors=H_A$color

down_num=dim(H_A%>%filter(log2FoldChange<=-1*lfc.cutoff)%>%filter(padj<=padj.cutoff))[1]

up_num=dim(H_A%>%filter(log2FoldChange>=lfc.cutoff)%>%filter(padj<=padj.cutoff))[1]

names(colors)[colors =='blue'] <- paste0('downregulated genes (', down_num, ')')
names(colors)[colors =='tomato2'] <- paste0('upregulated genes (', up_num, ')')
names(colors)[colors =='grey'] <- 'no significant change'

```
```{r}
volcano=EnhancedVolcano(H_A,
    lab = rownames(H_A),
    x = 'log2FoldChange',
    selectLab = NA,
    ylim = c(0, 55),
    xlim=c(-7, 7),
    y = 'padj',
    title = paste('Heatshock vs 0.2% Glucose Volcano Plot'),
    subtitle = "",
    colCustom = colors,
    pCutoff = padj.cutoff,
    FCcutoff = lfc.cutoff)

line.data <- data.frame(xintercept = c(4, 5, 6, -4, -5, -6), Lines = c("16", "32", "64", "16", "32", "64"))
```

```{r}
#png('PRINT/heatshock_volcano.png',units="in", width=10, height=7, res=300)
volcano+
  annotate("text", line.data$xintercept, y=50, hjust = .5, label = line.data$Lines, size = 5) +
  
  theme(axis.text.x = element_text(size = 16),
        axis.text.y = element_text(size = 16))+
  theme(legend.text = element_text(size=16))+
  theme(axis.title.x =element_text(size=16) )+
  theme(axis.title.y = element_text(size=16))+

scale_x_continuous(limits = c(-7, 7), breaks = c(-6, -4, -2, 0, 2, 4, 6))+
geom_segment(aes(x = 4 , y = -Inf, xend = 4, yend = 48), linetype=2, color='indianred') +
geom_segment(aes(x = 5 , y = -Inf, xend = 5, yend = 48), linetype=2, color='indianred') +
geom_segment(aes(x = 6 , y = -Inf, xend = 6, yend = 48), linetype=2, color='indianred') +
geom_segment(aes(x = -4 , y = -Inf, xend = -4, yend = 48), linetype=2, color='steelblue') +
geom_segment(aes(x = -5 , y = -Inf, xend = -5, yend = 48), linetype=2, color='steelblue') +
geom_segment(aes(x = -6 , y = -Inf, xend = -6, yend = 48), linetype=2, color='steelblue') +
  labs(caption='')
#dev.off()
```





# circle plot 

```
gene_meta$Start=as.integer(gene_meta$Start)
gene_meta$End=as.integer(gene_meta$End)

H_A$Geneid=rownames(H_A)
H_A=inner_join(gene_meta, H_A)

heatmap_HA=H_A %>% filter(Chr=="NZ_CP043845.1") %>%
  select(Chr, Start, End, log2FoldChange)

write.csv(heatmap_HA, 'Circle Plots/heatmap_HA.csv', row.names = FALSE)

```

